language: rust
cache: rust
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libgpgme11-dev
      - libgpg-error-dev
      - gcc-4.9
      - g++-4.9
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      env:
        CC=/usr/bin/gcc-4.9
        CXX=/usr/bin/g++-4.9
        GPGME_DEBUG=9 
        AUTOMAKE_VERSION=1.14.1 
        GETTEXT_VERSION=0.19.3
    - os: osx
      before_install:
        - brew update
        - brew install qt5
